sonar.projectKey=AlexanderVilla47_ci-project
sonar.organization=alexandervilla47
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=node_modules/**,coverage/**,src/public/**